spring.application.name=arcotcabs-backend
# AWS S3 CONFIG (REQUIRED)
aws.s3.bucket=arcot-cabs-storage2026
aws.s3.region=ap-south-1
server.address=0.0.0.0
server.port=9090
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
